version = "3.7.15"
runner.dialect = scala3
maxColumn = 140
fileOverride {
  "glob:**/extensions/k8s-service/sbt/src/main/scala/**" {
     runner.dialect = scala212
  }
  "glob:**/extensions/aws-lambda/sbt/src/main/scala/**" {
     runner.dialect = scala212
  }
}
