package yaga.codegen.k8sservice

import java.nio.file.Path
import tastyquery.Contexts.*
import tastyquery.Symbols.*
import yaga.codegen.core.generator.{ScalaMetaUtils, SourceFile, FilePath}
import yaga.codegen.core.generator.scalameta.interpolator.*
import yaga.codegen.core.extractor.{ModelExtractor as CoreModelExtractor}
import scala.meta.XtensionSyntax

class ModuleApiGenerator(packagePrefixParts: Seq[String], serviceAppApis: Seq[ExtractedServiceAppApi]):
  val apiModelSymbolSet = serviceAppApis.foldLeft(Set.empty[Symbol])(_ | _.modelSymbols.toSet)
  val apiModelSymbols = apiModelSymbolSet.toSeq
  val typeRenderer = TypeRenderer(packagePrefixParts, apiModelSymbolSet)

  println("&&&&&&&&&")

  serviceAppApis.flatMap(_.referencedSchemaableSymbols).foreach: sym =>
    println(sym)

  def generateModelSources()(using Context): Seq[SourceFile] =
    println("##################")
    apiModelSymbols.foreach(sym => println(s"Processing API model symbol: ${sym.name}"))
    println("$$$$$$$$$$$$$$$$$$")
    apiModelSymbols.flatMap:
      case sym: ClassSymbol if sym.isCaseClass =>
        Seq(sourceForCaseClass(sym))
      case sym =>
        throw Exception(s"Code generation unsupported for symbol: ${sym}")
         // TODO handle other types

  def sourceForCaseClass(sym: ClassSymbol)(using Context): SourceFile =
    val packagesSuffixParts = CoreModelExtractor.ownerPackageNamesChain(sym.owner)
    val packageParts = packagePrefixParts ++ packagesSuffixParts
    val packageRef = ScalaMetaUtils.packageRefFromParts(packageParts)
    val packageClause = Option.when(packageParts.nonEmpty)(m"package ${packageRef}")

    val className = scala.meta.Type.Name(sym.name.toString)
    val fieldLines = sym.tree.get.rhs.constr.paramLists match
      case Nil => Nil
      case List(Left(termParams)) =>
        termParams.map: param =>
          val fieldName = scala.meta.Term.Name(param.name.toString)
          val fieldType = typeRenderer.typeToCode(param.tpt.toType)
          m"  ${fieldName}: ${fieldType}"
      case lists =>
        throw Exception(s"Cannot generate code for class: ${sym} - only case classes with a single parameter list are supported")

    val sourceCode =
      m"""|/*
          | * This file was generated by yaga. Do not modify it manually!
          | */
          |
          |package ${packageRef}
          |
          |import _root_.besom.json.defaultProtocol
          |import _root_.besom.json.defaultProtocol.given
          |
          |final case class ${className} (
          |${fieldLines.mkString(",\n")}
          |) derives _root_.besom.json.JsonFormat
          |""".stripMargin
    SourceFile(
      FilePath(packageParts :+ s"${sym.name}.scala"),
      sourceCode
    )

  def generateSourcesForSchemaableTypes()(using Context): Seq[SourceFile] =
    serviceAppApis.flatMap(_.referencedSchemaableSymbols).map(sym => generateSourcesForSchemaableType(sym))

  def generateSourcesForSchemaableType(sym: ClassSymbol)(using Context): SourceFile =
    val packagesSuffixParts = CoreModelExtractor.ownerPackageNamesChain(sym.owner)
    val packageParts = packagePrefixParts ++ packagesSuffixParts
    val className = scala.meta.Type.Name(sym.name.toString) // TODO avoid name clashes?

    val fakeOpenApiSpecYaml = // TODO
      """
      |openapi: 3.1.0
      |info:
      |  title: Yaga service API
      |  version: ''
      |paths:
      |  /echo:
      |    post:
      |      operationId: postEcho
      |      requestBody:
      |        content:
      |          text/plain:
      |            schema:
      |              type: string
      |        required: true
      |      responses:
      |        '200':
      |          description: ''
      |          content:
      |            text/plain:
      |              schema:
      |                type: string
      """.stripMargin

    val trippleQuotes = "\"\"\""
    
    val sourceCode =
      m"""|/*
          | * This file was generated by yaga. Do not modify it manually!
          | */
          |
          |package ${ScalaMetaUtils.packageRefFromParts(packageParts)}
          |
          |trait ${className}
          |
          |object ${className}:
          |  given clientApiSchema: yaga.k8sservice.ClientApiSchema[${className}] with
          |    type Schema = clientApiSpecYaml.type
          |
          |  inline val clientApiSpecYaml = ${trippleQuotes}
          |${fakeOpenApiSpecYaml}
          |  ${trippleQuotes}
          |""".stripMargin

    SourceFile(
      FilePath(packageParts :+ s"${className}.scala"),
      sourceCode
    )

  def generateServiceAppResourceClasses(dockerContextPath: Path)(using Context): Seq[SourceFile] =
    serviceAppApis.map: serviceAppApi =>
      generateServiceAppResourceClass(serviceAppApi, dockerContextPath)

  def generateServiceAppResourceClass(serviceAppApi: ExtractedServiceAppApi, dockerContextPath: Path)(using Context): SourceFile =
    val packagesSuffixParts = serviceAppApi.serviceAppClassPackageParts
    val packageParts = packagePrefixParts ++ packagesSuffixParts
    lazy val packageRef = ScalaMetaUtils.packageRefFromParts(packageParts)
    val packageClause = Option.when(packageParts.nonEmpty)(m"package ${packageRef}")

    val resourceClassName = scala.meta.Type.Name(serviceAppApi.serviceAppClassName)
    val resourceArgsClassName = scala.meta.Type.Name(s"${serviceAppApi.serviceAppClassName}Args")
    val dockerContextPathConst = scala.meta.Lit.String(dockerContextPath.toString)

    val configTypeCode = typeRenderer.typeToCode(serviceAppApi.serviceAppConfigType)

    val defaultConfigValueSnippet = serviceAppApi.serviceAppConfigType.showBasic match // TODO handle other types in an extensible / more generic way
      case "scala.Unit" => " = ()"
      case _ => ""

    val trippleQuotes = "\"\"\""


    val sourceCode = 
      m"""|/*
          | * This file was generated by yaga. Do not modify it manually!
          | */
          |
          |${packageClause}

          |import yaga.kubernetes.DeployableImage
          |
          |import besom.*
          |import besom.api.kubernetes
          |
          |
          |final class ${resourceArgsClassName} private(
          |  val namespace: Output[String],
          |  val image: Output[${resourceClassName}.Image],
          |  val imageSecrets: Output[kubernetes.core.v1.Secret],
          |  val runConfig: Output[${resourceClassName}.RunConfig]
          |)
          |
          |object ${resourceArgsClassName} {
          |  def apply(
          |    namespace: Input[String],
          |    image: Input[${resourceClassName}.Image],
          |    imageSecrets: Input[kubernetes.core.v1.Secret],
          |    runConfig: Input[${resourceClassName}.RunConfig]${defaultConfigValueSnippet}
          |  ): ${resourceArgsClassName} = new ${resourceArgsClassName}(
          |    namespace = namespace.asOutput(),
          |    image = image.asOutput(),
          |    imageSecrets = imageSecrets.asOutput(),
          |    runConfig = runConfig.asOutput()
          |  )
          |}
          |
          |final case class ${resourceClassName} private(
          |  val appName: Output[String],
          |  val serviceName: Output[Option[String]],
          |  val deploymentName: Output[Option[String]],
          |  val namespace: Output[String],
          |) (using ComponentBase) extends ComponentResource, yaga.k8sservice.Service derives RegistersOutputs
          |
          |object ${resourceClassName} {
          |  case class Image private[${resourceClassName}](image: besom.api.docker.Image) extends yaga.kubernetes.DeployableImage[${resourceClassName}] derives Encoder:
          |    def imageReference: Output[String] = image.repoDigest
          |
          |  object Image:
          |    val dockerContextPath = ${dockerContextPathConst}
          |
          |
          |  def imageResource(resourceName: NonEmptyString, fullImageName: Input[String], registry: Input[besom.api.docker.inputs.RegistryArgs])(using Context): Output[Image] = {
          |    val image = besom.api.docker.Image(
          |      resourceName,
          |      besom.api.docker.ImageArgs(
          |        imageName = fullImageName,
          |        build = besom.api.docker.inputs.DockerBuildArgs(
          |          context = Image.dockerContextPath,
          |          platform = "linux/amd64"
          |        ),
          |        registry = registry
          |      )
          |    )
          |
          |    image.map(new Image(_))
          |  }
          |
          |  type RunConfig = ${configTypeCode}
          |
          |  def apply(
          |    name: NonEmptyString,
          |    args: ${resourceArgsClassName},
          |    opts: ResourceOptsVariant.Component ?=> ComponentResourceOptions = ComponentResourceOptions()
          |  )(using Context): Output[${resourceClassName}] = {
          |    val typ: ResourceType = "yaga:custom:${resourceClassName}" // TODO
          |
          |    val appLabel = name
          |
          |    val targetPort = 8080 // TODO
          |
          |    // TODO prevent undesired substitution of env variables done by pulumi kubernetes
          |    val configEnvVars = args.runConfig.map { config =>
          |      val envVarsMap = yaga.k8sservice.internal.EnvWriter.write(config)
          |      envVarsMap.map { case (name, value) => kubernetes.core.v1.inputs.EnvVarArgs(name = name, value = value) }
          |    }
          |
          |    val envVars = configEnvVars
          |
          |    besom.component(name, typ, opts(using ResourceOptsVariant.Component)) {
          |      val basicDeploymentArgs = kubernetes.apps.v1.DeploymentArgs(
          |        metadata = kubernetes.meta.v1.inputs.ObjectMetaArgs(
          |          name = p"$${name}-deployment",
          |          namespace = args.namespace
          |        ),
          |        spec = kubernetes.apps.v1.inputs.DeploymentSpecArgs(
          |          replicas = 1,
          |          selector = kubernetes.meta.v1.inputs.LabelSelectorArgs(
          |            matchLabels = Map("yaga-app" -> appLabel)
          |          ),
          |          template = kubernetes.core.v1.inputs.PodTemplateSpecArgs(
          |            metadata = kubernetes.meta.v1.inputs.ObjectMetaArgs(
          |              labels = Map("yaga-app" -> appLabel)
          |            ),
          |            spec = kubernetes.core.v1.inputs.PodSpecArgs(
          |              containers = List(kubernetes.core.v1.inputs.ContainerArgs(
          |                name = "yaga-app", // TODO
          |                image = args.image.imageReference, 
          |                ports = List(kubernetes.core.v1.inputs.ContainerPortArgs(containerPort = targetPort)), // TODO allow customization
          |                env = envVars
          |              )),
          |              imagePullSecrets = List(kubernetes.core.v1.inputs.LocalObjectReferenceArgs(name = args.imageSecrets.metadata.name))
          |            )
          |          )
          |        )
          |      )
          |
          |      val deploymentArgs = basicDeploymentArgs
          |
          |      val deployment = kubernetes.apps.v1.Deployment(s"$${name}-deployment", deploymentArgs)
          |
          |      val basicServiceArgs = kubernetes.core.v1.ServiceArgs(
          |        metadata = kubernetes.meta.v1.inputs.ObjectMetaArgs(
          |          name = p"$${name}-service",
          |          namespace = args.namespace
          |        ),
          |        spec = kubernetes.core.v1.inputs.ServiceSpecArgs(
          |          selector = Map("yaga-app" -> appLabel),
          |
          |
          |          // TODO
          |          ports = List(
          |            kubernetes.core.v1.inputs.ServicePortArgs(
          |              port = targetPort,
          |              targetPort = targetPort
          |            )
          |          ),
          |
          |          // TODO
          |          `type` = "NodePort" // for local dev (e.g., Minikube); LoadBalancer for cloud
          |          // `type` = "LoadBalancer"
          |        )
          |      )
          |
          |      val basicServiceAccountArgs = kubernetes.core.v1.ServiceAccountArgs(
          |        metadata = kubernetes.meta.v1.inputs.ObjectMetaArgs(
          |          name = name,
          |          namespace = args.namespace
          |        )
          |      )
          |
          |      val serviceAccountArgs = basicServiceAccountArgs
          |
          |      val serviceArgs = basicServiceArgs
          |
          |      val service = kubernetes.core.v1.Service(s"$${name}-service", serviceArgs)
          |
          |      new ${resourceClassName}(
          |        appName = Output(name),
          |        serviceName = service.metadata.name,
          |        deploymentName = deployment.metadata.name,
          |        namespace = args.namespace,
          |      )
          |    }
          |  }
          |
          |  given serverApiSchema[A <: ${resourceClassName}]: yaga.k8sservice.ServerApiSchema[A] with
          |    type Schema = serverApiSpecYaml.type
          |
          |  inline val serverApiSpecYaml = ${trippleQuotes}
          |${serviceAppApi.openApiSpecYaml}
          |  ${trippleQuotes}
          |}
          |""".stripMargin
    
    SourceFile(
      FilePath(packageParts :+ s"${serviceAppApi.serviceAppClassName}.scala"),
      sourceCode
    )
