name: Yaga build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6.4.3
      - uses: extractions/setup-just@v3.0.0
        with:
          just-version: '1.40.0'
      - uses: VirtusLab/scala-cli-setup@v1.7.1
        with:
          jvm: graalvm-java11:22.3.3
          apps: sbt
      - name: Clean compile library
        run: sbt "clean; compile"
      - name: Publish locally
        run: sbt "publishLocal"
      - name: Build examples
        run: ./scripts/buildExamples.sc
